# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('signup_date', models.DateTimeField()),
                ('fb_link', models.CharField(max_length=200)),
                ('tw_link', models.CharField(max_length=200)),
                ('insta_link', models.CharField(max_length=200)),
                ('gplus_link', models.CharField(max_length=200)),
                ('li_link', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('points', models.IntegerField()),
                ('num_persons', models.IntegerField()),
                ('referred_by', models.BigIntegerField()),
                ('num_chidren', models.IntegerField()),
                ('age_last_child', models.IntegerField()),
                ('session', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
