# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age_last_child',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_chidren',
        ),
    ]
