# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0002_auto_20170310_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fb_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gplus_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='insta_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='li_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tw_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
